Squashed third implementation
CJSCommonPlatform/json-generator pull request #2
Opened 2017-01-19 14:17 UTC by purple52

2017-01-23 10:57 UTC, allanmckenzie commented on src/main/java/uk/gov/justice/json/generator/JsonArrayGenerator.java
> +    }
This is a lot of logic to put in a constructor. Would an init() method be better?

2017-01-23 10:59 UTC, allanmckenzie commented on src/main/java/uk/gov/justice/json/generator/JsonArrayGenerator.java
> +    }
Is this fully tested? as in every path and every boolean condition? It's rather hard to see from this review code

2017-01-23 13:38 UTC, allanmckenzie approved these changes

2017-01-23 16:48 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/JsonArrayGenerator.java
> +            return itemGenerator.next();
Can itemGenerator ever be null? Why have a single itemGenerator and a List of itemGenerators?

2017-01-23 16:48 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/JsonCombinedSchemaGenerator.java
> +    public JsonCombinedSchemaGenerator(CombinedSchema combinedSchema) {
final?

2017-01-23 16:48 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/JsonCombinedSchemaGenerator.java
> +        return generator.next();
can generator be null?

2017-01-23 16:48 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/JsonCombinedSchemaGenerator.java
> +            getAnyOf(combinedSchema);
The method name does not seem to describe what is occurring here

2017-01-23 16:48 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/JsonCombinedSchemaGenerator.java
> +    private void getAnyOf(CombinedSchema combinedSchema) {
final

2017-01-23 16:48 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/JsonNumberGenerator.java
> +        IntegerGenerator.Builder builder = IntegerGenerator.builder();
final

2017-01-23 16:48 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/JsonNumberGenerator.java
> +        BigDecimalGenerator.Builder builder = BigDecimalGenerator.builder();
final

2017-01-23 16:48 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/JsonObjectGenerator.java
> +        Map<String, Schema> propertySchemas = schema.getPropertySchemas();
Multiple calls to schema.getPropertySchemas(), need only call once.

2017-01-23 16:48 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/JsonReferenceGenerator.java
> +    public JsonReferenceGenerator(ReferenceSchema referenceSchema) {
final

2017-02-07 12:43 UTC, mapingo requested changes

2017-02-07 12:43 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/ValueGenerator.java
> +    public ValueGenerator(Collection possibleValues) {
possibleValues can be final

2017-02-07 12:43 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/ValueGenerator.java
> +        Random random = new Random();
final

2017-02-07 12:43 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/jsonvalue/EnumJsonValueGenerator.java
> +    public EnumJsonValueGenerator(EnumSchema schema) {
schema can be final

2017-02-07 12:43 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/jsonvalue/EnumJsonValueGenerator.java
> +    private Object randomlyGet(Set<Object> possibleValues) {
final

2017-02-07 12:43 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/value/number/BigDecimalGenerator.java
> +    private BigDecimalGenerator(BigDecimalGenerator.Builder builder) {
builder can be final

2017-02-07 12:43 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/value/number/BigDecimalGenerator.java
> +        public BigDecimalGenerator.Builder exclusiveMaximum(boolean exclusiveMaximum) {
can be final and in other methods below

2017-02-07 12:43 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/value/number/IntegerGenerator.java
> +    private IntegerGenerator(IntegerGenerator.Builder builder) {
final

2017-02-07 12:43 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/value/number/IntegerGenerator.java
> +        int maximum = this.maximum.get();
these could be final

2017-02-07 12:43 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/value/number/IntegerGenerator.java
> +        public IntegerGenerator.Builder exclusiveMaximum(boolean exclusiveMaximum) {
can be final and methods below

2017-02-07 12:43 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/value/string/RegexGenerator.java
> +    public RegexGenerator(Pattern pattern) {
pattern can be final

2017-02-07 12:43 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/value/string/SimpleStringGenerator.java
> +    public SimpleStringGenerator(int minLength, int maxLength) {
final

2017-02-07 12:43 UTC, mapingo commented on src/test/java/uk/gov/justice/json/MatcherBasedTypeCheck.java
> +            T next = generator.next();
final

2017-02-07 12:43 UTC, mapingo commented on src/test/java/uk/gov/justice/json/MatcherBasedTypeCheck.java
> +        private Times(int num) {
final and below

2017-02-07 12:43 UTC, mapingo commented on src/test/java/uk/gov/justice/json/generator/EnumJsonValueGeneratorTest.java
> +        EnumJsonValueGenerator jsonEnumGenerator = new EnumJsonValueGenerator((EnumSchema) schema);
final

2017-02-07 12:43 UTC, mapingo commented on src/test/java/uk/gov/justice/json/generator/EnumJsonValueGeneratorTest.java
> +        EnumJsonValueGenerator jsonEnumGenerator = new EnumJsonValueGenerator((EnumSchema) schema);
final and other tests below

2017-02-07 12:43 UTC, mapingo commented on src/test/java/uk/gov/justice/json/generator/JsonStringGeneratorTest.java
> +    private Optional<String> validate(FormatValidator validator,JsonValue jsonValue){
final

2017-02-07 12:43 UTC, mapingo commented on src/test/java/uk/gov/justice/json/generator/matcher/JsonValueSchemaMatcher.java
> +    private static Boolean validateJsonObject(Schema schema, JsonValue jsonValue) {
final

2017-02-07 12:43 UTC, mapingo commented on src/test/java/uk/gov/justice/json/generator/multivalue/ArrayGeneratorTest.java
> +//        assertThat(arrayValueGenerator.nextValue(), is("[23,\"Fred Bloggs\",{\"property\": true}]"));
nothing being tested here, commented out assertion

2017-02-07 12:43 UTC, mapingo commented on src/test/java/uk/gov/justice/json/generator/value/EmailGeneratorTest.java
> +        System.out.println(jsonEmailValue);
System.out can be removed

2017-02-07 12:43 UTC, mapingo commented on src/test/java/uk/gov/justice/json/generator/value/StringValueGeneratorTest.java
> +        SimpleStringGenerator stringValueGenerator = new SimpleStringGenerator(4,12);
final

2017-02-07 12:43 UTC, mapingo commented on src/test/java/uk/gov/justice/json/generator/value/StringValueGeneratorTest.java
> +        SimpleStringGenerator stringValueGenerator = new SimpleStringGenerator(4,12);
final

2017-02-07 12:43 UTC, mapingo commented on src/test/java/uk/gov/justice/json/generator/value/UriGeneratorTest.java
> +//        assertThat(true, is(regexValidator.isValid(uriAddress)));
nothing tested here

2017-02-07 13:20 UTC, mapingo commented on src/main/java/uk/gov/justice/json/generator/JsonArrayGenerator.java
> +        JsonArrayBuilder builder = createArrayBuilder();
could be final

2017-02-10 10:40 UTC, purple52 commented on src/main/java/uk/gov/justice/json/generator/JsonArrayGenerator.java
> +    }
It isn't really logic - it's extracting from the schema and setting up the generator. We have spiked and compared with static builder methods (see https://github.com/CJSCommonPlatform/json-generator/tree/factory-methods). The code was slightly nicer, but it doesn't buy us enough right now to rewrite everything. We might want to refactor gradually after this is merged.

2017-02-10 10:41 UTC, purple52 commented on src/main/java/uk/gov/justice/json/generator/JsonArrayGenerator.java
> +            return itemGenerator.next();
This weirdness is due to how JSON schemas work. We should refactor at some point to make this cleaner.

2017-02-10 13:46 UTC, purple52 commented on src/main/java/uk/gov/justice/json/generator/value/number/BigDecimalGenerator.java
> +        public BigDecimalGenerator.Builder exclusiveMaximum(boolean exclusiveMaximum) {
Not going to fix these much. BigDecimalGenerator and IntegerGenerator need rewriting.

2017-02-15 16:02 UTC, mapingo approved these changes

2017-02-15 16:02 UTC, merged